###############################################################################
# THE PATH
###############################################################################
export PATH=/home/lorenzo/bin:/usr/local/bin:/bin:/opt/bin:~/go/bin/:~/.local/bin:~/.cargo/bin:$PATH:/data/flutter/bin
###############################################################################
# THE HOME
###############################################################################
export ZSH=$HOME/.config/zsh
###############################################################################
# THE EDITOR
###############################################################################
export EDITOR=/usr/bin/nvim
###############################################################################
# THE HISTORY
###############################################################################
export HISTFILE=$HOME/.zsh_history
# How many commands zsh will load to memory.
export HISTSIZE=50000
# number of lines
export HISTFILESIZE=50000
# How many commands history will save on file.
export SAVEHIST=50000
# History won't save duplicates.
setopt HIST_IGNORE_ALL_DUPS
# History won't show duplicates on search.
setopt HIST_FIND_NO_DUPS
###############################################################################
# PLUGINS
###############################################################################
source $ZSH/plugins/atareao/atareao.plugin.zsh
source $ZSH/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fpath=($ZSH/plugins/zsh-completions/src $fpath)
fpath=($ZSH/plugins/custom-completions $fpath)
autoload -Uz compinit
compinit
###############################################################################
# STARSHIP
###############################################################################
export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init zsh)"
###############################################################################
# ZOXIDE
###############################################################################
eval "$(zoxide init zsh)"
###############################################################################
# TERE
###############################################################################
tere() {
    local result=$(command tere "$@")
    [ -n "$result" ] && cd -- "$result"
}
###############################################################################
# SK
###############################################################################
# if which sk > /dev/null;then
#     if [[ -f ~/.config/sk/key-bindings.zsh && -r ~/.config/sk/key-bindings.zsh ]]; then
#         source ~/.config/sk/key-bindings.zsh
#     fi
# fi
###############################################################################
# BROOT 
###############################################################################
source /home/lorenzo/.config/broot/launcher/bash/br
###############################################################################
# KEYBINDINGS as emacs
###############################################################################
bindkey -e
###
# DOCKER
###
export DOCKER_HOST=unix://${XDG_RUNTIME_DIR}/docker.sock
### OPEN_AI
#token=$(grep token ~/.cargo/bin/oye.yml)
#export OPENAI_API_KEY="${token##* }"
### ATUIN
eval "$(atuin init zsh)"
bindkey '^P' _atuin_up_search_widget
export TRASH_DIR=~/.trashdir
### VALE
export VALE_CONFIG_PATH=~/.config/vale/vale.ini
