--
vim.keymap.set("n", "<leader>0","<Plug>(cokeline-focus-0)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>1","<Plug>(cokeline-focus-1)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>2","<Plug>(cokeline-focus-2)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>3","<Plug>(cokeline-focus-3)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>4","<Plug>(cokeline-focus-4)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>5","<Plug>(cokeline-focus-5)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>6","<Plug>(cokeline-focus-6)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>7","<Plug>(cokeline-focus-7)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>8","<Plug>(cokeline-focus-8)", {silent = true, noremap = true, nowait = true})
vim.keymap.set("n", "<leader>9","<Plug>(cokeline-focus-0)", {silent = true, noremap = true, nowait = true})
