#! /bin/sh

pkill sxhkd
sxhkd &

pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &

pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

pkill xautolock
xautolock -time 5 -locker "betterlockscreen -l" -notify 30 -notifier "notify-send 'Locker' 'Locking screen in 30 seconds'" -killtime 5 -killer "systemctl suspend" &

"${HOME}/.config/polybar/material/launch.sh"

feh --bg-scale "${HOME}/Imágenes/potd.jpg" &

bspc monitor HDMI-A-0 -d I II III IV V VI
bspc monitor DisplayPort-0 -d VII VIII XI X

bspc config border_width          2
bspc config window_gap            10
bspc config top_padding           0
# bspc config bottom_padding       80
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_follows_focus true

bspc config automatic_scheme  	  alternate
bspc config removal_adjustment
bspc config honor_size_hints
bspc config ignore_ewmh_struts

bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

# For Pycharm and Intellj
wmname LG3D

#BSPWM coloring
bspc config normal_border_color		"#1f1f1f"
bspc config active_border_color		"#1f1f1f"
bspc config focused_border_color	"#ffb300"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

bspc rule -a Gimp desktop='^2' state=floating follow=on
bspc rule -a Chromium desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Rofi focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty desktop='^1'
bspc rule -a Firefox desktop='^7'
bspc rule -a Ardour desktop='^8'
bspc rule -a Evince desktop='^2'
bspc rule -a TelegramDesktop desktop='^2'


