#! /bin/sh

pkill sxhkd
sxhkd &

$HOME/.config/polybar/launcher.sh
# compton --config $HOME/.config/compton/compton.conf &
pkill picom
picom --daemon --config $HOME/.config/picom/picom.conf &
feh --bg-scale $HOME/.config/daily-wallpaper/potd.jpg &

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor DVI-I-1-1 -d I II III IV V
bspc monitor HDMI-1 -d V VI VII VIII XI X
bspc monitor HDMI-2 -d I II III IV
# bspc monitor eDP-1 -d VII VIII IX

bspc config border_width          2
bspc config window_gap            5
bspc config top_padding           0
#bspc config bottom_padding       80
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_follows_focus true

# For Pycharm and Intellj
wmname LG3D

#BSPWM coloring
bspc config normal_border_color		"#ffc199"
bspc config active_border_color		"#ffc199"
bspc config focused_border_color	"#dc5800"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

bspc rule -a Gimp desktop='^1' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Rofi focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty desktop='^7'
bspc rule -a Firefox desktop='^1'
bspc rule -a Ardour desktop='^8'
bspc rule -a Evince desktop='^1'
bspc rule -a TelegramDesktop desktop='^1'

dunst -conf ~/.config/dunst/dunstrc &
