config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_custom.aliases.bash:
    src: bash_it/aliases/custom.aliases.bash
    dst: ~/.bash_it/aliases/custom.aliases.bash
  f_custom.completion.bash:
    src: bash_it/completion/custom.completion.bash
    dst: ~/.bash_it/completion/custom.completion.bash
  f_custom.bash:
    src: bash_it/lib/custom.bash
    dst: ~/.bash_it/lib/custom.bash
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_face:
    src: face
    dst: ~/.face
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_espanso:
    src: config/espanso
    dst: ~/.config/espanso
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  d_lib:
    src: bash_it/lib
    dst: ~/.bash_it/lib
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_fzf-completion.bash:
    src: bash_it/completion/fzf-completion.bash
    dst: ~/.bash_it/completion/fzf-completion.bash
  f_fzf-key-bindings.bash:
    src: bash_it/completion/fzf-key-bindings.bash
    dst: ~/.bash_it/completion/fzf-key-bindings.bash
  f_aliases.zsh:
    src: oh-my-zsh/custom/aliases.zsh
    dst: ~/.oh-my-zsh/custom/aliases.zsh
  d_atareao:
    src: oh-my-zsh/custom/plugins/atareao
    dst: ~/.oh-my-zsh/custom/plugins/atareao
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
variables:
  dotfilesdir: /datos/misdotfiles
profiles:
  gk55:
    dotfiles:
    - f_custom.aliases.bash
    - f_custom.completion.bash
    - f_custom.bash
    - f_rc.conf
    - f_face
    - d_kitty
    - d_bspwm
    - d_espanso
    - d_polybar
    - d_rofi
    - d_sxhkd
    - f_bashrc
    - d_lib
    - d_nvim
    - f_fzf-completion.bash
    - f_fzf-key-bindings.bash
    - f_aliases.zsh
    - d_atareao
    - f_zshrc
  raspiarch:
    dotfiles:
    - f_custom.aliases.bash
    - f_custom.completion.bash
    - f_custom.bash
    - f_rc.conf
    - f_bashrc
    - d_lib
    - d_nvim
    - f_fzf-completion.bash
    - f_fzf-key-bindings.bash
    variables:
      dotfilesdir: ~/dotfiles
