config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_face:
    src: face
    dst: ~/.face
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_espanso:
    src: config/espanso
    dst: ~/.config/espanso
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_aliases.zsh:
    src: oh-my-zsh/custom/aliases.zsh
    dst: ~/.oh-my-zsh/custom/aliases.zsh
  d_atareao:
    src: oh-my-zsh/custom/plugins/atareao
    dst: ~/.oh-my-zsh/custom/plugins/atareao
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_picom.conf:
    src: config/picom/picom.conf
    dst: ~/.config/picom/picom.conf
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_backup.sh:
    src: local/bin/backup.sh
    dst: ~/.local/bin/backup.sh
    chmod: '755'
  d_user:
    src: config/systemd/user
    dst: ~/.config/systemd/user
  d_gitui:
    src: config/gitui
    dst: ~/.config/gitui
  f_betterlockscreenrc:
    src: config/betterlockscreenrc
    dst: ~/.config/betterlockscreenrc
  f_backup.service:
    src: config/systemd/user/backup.service
    dst: ~/.config/systemd/user/backup.service
  f_backup.timer:
    src: config/systemd/user/backup.timer
    dst: ~/.config/systemd/user/backup.timer
  f_betterlockscreen@.service:
    src: config/systemd/user/betterlockscreen@.service
    dst: ~/.config/systemd/user/betterlockscreen@.service
variables:
  dotfilesdir: /datos/misdotfiles
profiles:
  gk55:
    dotfiles:
    - f_rc.conf
    - f_face
    - d_kitty
    - d_bspwm
    - d_espanso
    - d_polybar
    - d_rofi
    - d_sxhkd
    - d_nvim
    - f_aliases.zsh
    - d_atareao
    - f_zshrc
    - f_picom.conf
    - f_dunstrc
    - f_backup.sh
    - d_user
    - d_gitui
    - f_betterlockscreenrc
    - f_backup.service
    - f_backup.timer
    - f_betterlockscreen@.service
  raspiarch:
    dotfiles:
    - f_rc.conf
    - d_nvim
    variables:
      dotfilesdir: ~/dotfiles
