config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_custom.aliases.bash:
    src: bash_it/aliases/custom.aliases.bash
    dst: ~/.bash_it/aliases/custom.aliases.bash
  f_custom.completion.bash:
    src: bash_it/completion/custom.completion.bash
    dst: ~/.bash_it/completion/custom.completion.bash
  f_custom.bash:
    src: bash_it/lib/custom.bash
    dst: ~/.bash_it/lib/custom.bash
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_face:
    src: face
    dst: ~/.face
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_espanso:
    src: config/espanso
    dst: ~/.config/espanso
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  d_lib:
    src: bash_it/lib
    dst: ~/.bash_it/lib
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  gk55:
    dotfiles:
    - f_custom.aliases.bash
    - f_custom.completion.bash
    - f_custom.bash
    - f_rc.conf
    - f_face
    - d_kitty
    - d_bspwm
    - d_espanso
    - d_polybar
    - d_rofi
    - d_sxhkd
    - f_bashrc
    - d_lib
    - d_nvim
