config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_rc.conf:
    src: config/ranger/rc.conf
    dst: ~/.config/ranger/rc.conf
  f_face:
    src: face
    dst: ~/.face
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_espanso:
    src: config/espanso
    dst: ~/.config/espanso
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_aliases.zsh:
    src: oh-my-zsh/custom/aliases.zsh
    dst: ~/.oh-my-zsh/custom/aliases.zsh
  d_atareao:
    src: oh-my-zsh/custom/plugins/atareao
    dst: ~/.oh-my-zsh/custom/plugins/atareao
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_picom.conf:
    src: config/picom/picom.conf
    dst: ~/.config/picom/picom.conf
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_backup.sh:
    src: local/bin/backup.sh
    dst: ~/.local/bin/backup.sh
    chmod: '755'
  d_gitui:
    src: config/gitui
    dst: ~/.config/gitui
  f_betterlockscreenrc:
    src: config/betterlockscreenrc
    dst: ~/.config/betterlockscreenrc
  f_backup.service:
    src: config/systemd/user/backup.service
    dst: ~/.config/systemd/user/backup.service
  f_backup.timer:
    src: config/systemd/user/backup.timer
    dst: ~/.config/systemd/user/backup.timer
  f_betterlockscreen@.service:
    src: config/systemd/user/betterlockscreen@.service
    dst: ~/.config/systemd/user/betterlockscreen@.service
  f_config.yaml:
    src: config/efm-langserver/config.yaml
    dst: ~/.config/efm-langserver/config.yaml
  f_dnoterc:
    src: config/dnote/dnoterc
    dst: ~/.config/dnote/dnoterc
  f_rofimoji.rc:
    src: config/rofimoji.rc
    dst: ~/.config/rofimoji.rc
  f_fonts.conf:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  f_default.pa:
    src: config/pulse/default.pa
    dst: ~/.config/pulse/default.pa
  d_basic:
    src: config/obs-studio/basic
    dst: ~/.config/obs-studio/basic
  f_global.ini:
    src: config/obs-studio/global.ini
    dst: ~/.config/obs-studio/global.ini
  f_starship.toml:
    src: config/starship/starship.toml
    dst: ~/.config/starship/starship.toml
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_eww:
    src: config/eww
    dst: ~/.config/eww
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  f_config:
    src: config/cava/config
    dst: ~/.config/cava/config
  f_zellij_config.yaml:
    src: config/zellij/config.yaml
    dst: ~/.config/zellij/config.yaml
  f_wezterm.lua:
    src: config/wezterm/wezterm.lua
    dst: ~/.config/wezterm/wezterm.lua
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  f_justfile:
    src: Vídeos/.justfile
    dst: ~/Vídeos/.justfile
  f_blocks_justfile:
    src: php/blocks/.justfile
    dst: ~/php/blocks/.justfile
  d_i3:
    src: config/i3
    dst: ~/.config/i3
variables:
  dotfilesdir: /datos/misdotfiles
profiles:
  one:
    dotfiles:
    - f_rc.conf
    - f_face
    - d_kitty
    - d_bspwm
    - d_espanso
    - d_polybar
    - d_rofi
    - d_sxhkd
    - d_nvim
    - f_aliases.zsh
    - d_atareao
    - f_zshrc
    - f_picom.conf
    - f_dunstrc
    - f_backup.sh
    - d_gitui
    - f_betterlockscreenrc
    - f_backup.service
    - f_backup.timer
    - f_betterlockscreen@.service
    - f_config.yaml
    - f_dnoterc
    - f_rofimoji.rc
    - f_fonts.conf
    - f_default.pa
    - d_basic
    - f_global.ini
    - f_starship.toml
    - d_sway
    - d_eww
    - d_waybar
    - d_swaylock
    - f_config
    - f_zellij_config.yaml
    - f_wezterm.lua
    - d_hypr
    - f_justfile
    - f_blocks_justfile
    - d_i3
  raspiarch:
    dotfiles:
    - f_rc.conf
    - d_nvim
    variables:
      dotfilesdir: ~/dotfiles
