font_family      family="VictorMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
#font_family      IosevkaTerm Nerd Font Mono
#bold_font        IosevkaTerm Nerd Font Mono Medium
##italic_font      IosevkaTerm Nerd Font Mono Italic
#bold_italic_font IosevkaTerm Nerd Font Mono Bold Italic
font_size        11.0

bold_is_bright yes
# Gestión de ligaduras: se desactivan al pasar el cursor (útil para programar)
disable_ligatures cursor
