# Kaolin
# Theme create by: https://github.com/AnshumanNeon
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-macchiato"

# ========= Border =========
file_panel_border = "#74b09a"
sidebar_border = "#17171a"
footer_border = "#74b09a"

# ========= Border Active =========
file_panel_border_active = "#74b09a"
sidebar_border_active = "#57b2c2"
footer_border_active = "#57b2c2"
modal_border_active = "#868686"

# ========= Background (bg) =========
full_screen_bg = "#17171a"
file_panel_bg = "#17171a"
sidebar_bg = "#17171a"
footer_bg = "#17171a"
modal_bg = "#17171a"

# ========= Foreground (fg) =========
full_screen_fg = "#efefef"
file_panel_fg = "#efefef"
sidebar_fg = "#efefef"
footer_fg = "#efefef"
modal_fg = "#efefef"

# ========= Special Color =========
cursor = "#f5c791"
correct = "#74b09a"
error = "#c74a4d"
hint = "#4fa8a3"
cancel = "#d7936d"
# Gradient color can only have two color!
gradient_color = ["#74b09a", "#c74a4d"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#f5c791"
file_panel_top_path = "#d7936d"
file_panel_item_selected_fg = "#4fa8a3"
file_panel_item_selected_bg = "#17171a"

# ========= Sidebar Special Items =========
sidebar_title = "#f5c791"
sidebar_item_selected_fg = "#ba667d"
sidebar_item_selected_bg = "#17171a"
sidebar_divider = "#868686"

# ========= Modal Special Items =========
modal_cancel_fg = "#eedcc1"
modal_cancel_bg = "#c74a4d"

modal_confirm_fg = "#eedcc1"
modal_confirm_bg = "#3e594a"

# ========= Help Menu =========
help_menu_hotkey = "#4fa8a3"
help_menu_title = "#f5c791"