# OneDark
# Theme create by: https://github.com/CommandJoo
# Update by(sort by time):
#
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "onedark"

# ========= Border =========
file_panel_border = "#737994" # Overlay0
sidebar_border = "#737994"    # Base
footer_border = "#737994"     # Overlay0

# ========= Border Active =========
file_panel_border_active = "#57A5E5" # Lavendar
sidebar_border_active = "#DE5D68"    # Red
footer_border_active = "#8FB573"     # Green
modal_border_active = "#51A8B3"      # Overlay2

# ========= Background (bg) =========
full_screen_bg = "#2C2D31" # Base
file_panel_bg = "#232326"  # Base
sidebar_bg = "#232326"     # Base
footer_bg = "#232326"      # Base
modal_bg = "#35363B"       # Base

# ========= Foreground (fg) =========
full_screen_fg = "#A7AAB0" # Subtext0
file_panel_fg = "#A7AAB0"  # Subtext0
sidebar_fg = "#A7AAB0"     # Subtext0
footer_fg = "#A7AAB0"      # Subtext0
modal_fg = "#A7AAB0"       # Subtext0

# ========= Special Color =========
cursor = "#68AEE8"  # Rosewater
correct = "#a6d189" # Green
error = "#DE5D68"   # Red
hint = "#68AEE8"    # Sapphire
cancel = "#C49060"  # Maroon
# Gradient color can only have two color!
gradient_color = ["#68AEE8", "#BB70D2"] # [Blue, Mauve]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#DBB671" # Green
file_panel_top_path = "#DBB671"           # Blue
file_panel_item_selected_fg = "#51A8B3"   # Sky
file_panel_item_selected_bg = "#2C2D31"   # Base

# ========= Sidebar Special Items =========
sidebar_title = "#57A5E5"            # Sapphire
sidebar_item_selected_fg = "#51A8B3" # Sky
sidebar_item_selected_bg = "#2C2D31" # Base
sidebar_divider = "#818387"          # Overlay2

# ========= Modal Special Items =========
modal_cancel_fg = "#414559" # Surface0
modal_cancel_bg = "#DE5D68" # Maroon

modal_confirm_fg = "#414559" # Surface0
modal_confirm_bg = "#51A8B3" # Sky

# ========= Help Menu =========
help_menu_hotkey = "#51A8B3" # Sky
help_menu_title = "#BB70D2"  # Maroon
