#!/usr/bin/env bash
# -*- coding: utf-8 -*-

# Copyright (c) 2022 Lorenzo Carbonell <a.k.a. atareao>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

SLEEP_TIME=0.01
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export SCRIPT_DIR

function kp(){
    PROCESS="$1"
    pgrep "$PROCESS" | xargs -r kill -9
    while pgrep "$PROCESS";do
        sleep $SLEEP_TIME
    done
}

start_xrandr(){
    echo "Configuring monitors"
    # Configure monitors
    xrandr \
      --output DisplayPort-0 --auto --mode 1920x1080 --pos 0x0 \
      --output HDMI-A-0      --primary    --mode 1920x1080 --right-of DisplayPort-0
}

start_picom(){
    echo "Starting: picom"
    kp picom
    picom -f -b --experimental-backends --config "${SCRIPT_DIR}"/picom/picom.conf &
}

start_redshift(){
    echo "Starting: redshift"
    kp redshift
    redshift -m randr -x
    redshift -m randr -l 39.3627:-0.4120 &>/dev/null &
}

start_dunst(){
    echo "Starting: dunst"
    kp dunst
    dunst -conf "${SCRIPT_DIR}"/dunst/dunstrc &
}

start_feh(){
    echo "Starting: feh"
    kp feh
    feh --bg-scale "${SCRIPT_DIR}"/background/background.jpg &
}

start_polybar(){
    echo "Starting: polybar"
    kp polybar
    index=0 monitor=DisplayPort-0 width=1904 polybar -c "${SCRIPT_DIR}"/polybar/polybar.config mainbar0 &> /dev/null &
    index=1 monitor=HDMI-A-0 width=1904 polybar -c "${SCRIPT_DIR}"/polybar/polybar.config mainbar1 &> /dev/null &
}

start_xrandr
start_picom
start_redshift
start_dunst
start_feh
start_polybar
leftwm-command "LoadTheme ${SCRIPT_DIR}/theme/theme.ron"


