alias vim=nvim
alias vimdiff='nvim -d'
alias sshk='kitty +kitten ssh'
alias icat='kitty +kitten icat'
alias mydiff='kitty +kitten diff'
alias ls=lsd
alias du=dust
alias dcu='docker compose up -d'
alias dcp='docker compose ps'
alias dcr='docker compose up -d --force-recrate'
alias dcl='docker compose logs -f'
alias dcd='docker compose down'
alias dc='docker compose'
alias pc='podman compose'
alias pcu='podman compose up -d'
alias pcr='podman compose up -d --force-recreate'
alias pcp='podman compose ps'
alias pcl='podman compose logs -f'
alias pcd='podman compose dowdown'
alias rgi=sk --ansi -i -c 'rg --color=always --line-number "{}"'
alias mu=muc --file ~/.zsh_history --count 10 --pretty
alias hx=helix
alias play=ansible-playbook
alias tls="trasher ls"
alias trm="trasher rm"
