log_info = "debug"
url = "https://raw.githubusercontent.com/atareao/gitignore/main"
templates = [
"AL",
"Actionscript",
"Ada",
"Agda",
"Android",
"AppEngine",
"AppceleratorTitanium",
"ArchLinuxPackages",
"Autotools",
"C++",
"C",
"CFWheels",
"CMake",
"CUDA",
"CakePHP",
"ChefCookbook",
"Clojure",
"CodeIgniter",
"CommonLisp",
"Composer",
"Concrete5",
"Coq",
"CraftCMS",
"D",
"DM",
"Dart",
"Delphi",
"Drupal",
"EPiServer",
"Eagle",
"Elisp",
"Elixir",
"Elm",
"Erlang",
"ExpressionEngine",
"ExtJs",
"Fancy",
"Finale",
"FlaxEngine",
"ForceDotCom",
"Fortran",
"FuelPHP",
"GWT",
"Gcov",
"GitBook",
"Go",
"Godot",
"Gradle",
"Grails",
"Haskell",
"IGORPro",
"Idris",
"JBoss",
"JENKINS_HOME",
"Java",
"Jekyll",
"Joomla",
"Julia",
"KiCad",
"Kohana",
"Kotlin",
"LabVIEW",
"Laravel",
"Leiningen",
"LemonStand",
"Lilypond",
"Lithium",
"Lua",
"Magento",
"Maven",
"Mercury",
"MetaProgrammingSystem",
"Nanoc",
"Nim",
"Node",
"OCaml",
"Objective-C",
"Opa",
"OpenCart",
"OracleForms",
"Packer",
"Perl",
"Phalcon",
"PlayFramework",
"Plone",
"Prestashop",
"Processing",
"PureScript",
"Python",
"Qooxdoo",
"Qt",
"R",
"ROS",
"Racket",
"Rails",
"Raku",
"RhodesRhomobile",
"Ruby",
"Rust",
"SCons",
"Sass",
"Scala",
"Scheme",
"Scrivener",
"Sdcc",
"SeamGen",
"SketchUp",
"Smalltalk",
"Stella",
"SugarCRM",
"Swift",
"Symfony",
"SymphonyCMS",
"TeX",
"Terraform",
"Textpattern",
"TurboGears2",
"TwinCAT3",
"Typo3",
"Unity",
"UnrealEngine",
"VVVV",
"VisualStudio",
"Waf",
"WordPress",
"Xojo",
"Yeoman",
"Yii",
"ZendFramework",
"Zephir"
]
