# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#81c8be" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e5c890", bold = true, italic = true, underline = true }
find_position = { fg = "#f4b8e4", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#a6d189", bg = "#a6d189" }
marker_cut      = { fg = "#e78284", bg = "#e78284" }
marker_marked   = { fg = "#81c8be", bg = "#81c8be" }
marker_selected = { fg = "#e5c890", bg = "#e5c890" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#303446", bg = "#a6d189" }
count_cut      = { fg = "#303446", bg = "#e78284" }
count_selected = { fg = "#303446", bg = "#e5c890" }

# Border
border_symbol = "│"
border_style  = { fg = "#838ba7" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#303446", bg = "#8caaee", bold = true }
normal_alt  = { fg = "#8caaee", bg = "#414559" }

# Select mode
select_main = { fg = "#303446", bg = "#a6d189", bold = true }
select_alt  = { fg = "#a6d189", bg = "#414559" }

# Unset mode
unset_main = { fg = "#303446", bg = "#eebebe", bold = true }
unset_alt  = { fg = "#eebebe", bg = "#414559" }

# : }}}


# : Status bar {{{

[status]
separator_open  = ""
separator_close = ""

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8caaee", bg = "#51576d" }
progress_error  = { fg = "#e78284", bg = "#51576d" }

# Permissions
perm_sep   = { fg = "#838ba7" }
perm_type  = { fg = "#8caaee" }
perm_read  = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec  = { fg = "#a6d189" }

# TODO: -- remove these once Yazi 0.4 gets released
separator_style = { fg = "#414559", bg = "#414559" }
mode_normal     = { fg = "#303446", bg = "#8caaee", bold = true }
mode_select     = { fg = "#303446", bg = "#a6d189", bold = true }
mode_unset      = { fg = "#303446", bg = "#eebebe", bold = true }
permissions_t   = { fg = "#8caaee" }
permissions_r   = { fg = "#e5c890" }
permissions_w   = { fg = "#e78284" }
permissions_x   = { fg = "#a6d189" }
permissions_s   = { fg = "#838ba7" }
# TODO: remove these once Yazi 0.4 gets released --

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#8caaee" }
active   = { fg = "#f4b8e4", bold = true }
inactive = {}

# TODO: -- remove these once Yazi 0.4 gets released
[select]
border   = { fg = "#8caaee" }
active   = { fg = "#f4b8e4", bold = true }
inactive = {}
# TODO: remove these once Yazi 0.4 gets released --

# : }}}


# : Input {{{

[input]
border   = { fg = "#8caaee" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "#8caaee" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#8caaee" }
title   = {}
hovered = { fg = "#f4b8e4", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#414559" }
cand            = { fg = "#81c8be" }
rest            = { fg = "#949cbb" }
desc            = { fg = "#f4b8e4" }
separator       = "  "
separator_style = { fg = "#626880" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#81c8be" }
run     = { fg = "#f4b8e4" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#414559", bg = "#c6d0f5" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#a6d189" }
title_warn  = { fg = "#e5c890" }
title_error = { fg = "#e78284" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#81c8be" },

	# Media
	{ mime = "{audio,video}/*", fg = "#e5c890" },

	# Archives
	{ mime = "application/*zip", fg = "#f4b8e4" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f4b8e4" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#a6d189" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },
	{ name = "*/", fg = "#8caaee" }
]

# : }}}
