# GIT
[[cable_channel]]
name = "diff"
source_command = "git diff --name-only"
preview_command = "git diff --color=always {0}"

[[cable_channel]]
name = "reflog"
source_command = 'git reflog'
preview_command = 'git show -p --stat --pretty=fuller --color=always {0}'

[[cable_channel]]
name = "log"
source_command = "git log --oneline --date=short --pretty=\"format:%h %s %an %cd\" \"$@\""
preview_command = "git show -p --stat --pretty=fuller --color=always {0}"

[[cable_channel]]
name = "branch"
source_command = "git --no-pager branch --all --format=\"%(refname:short)\""
preview_command = "git show -p --stat --pretty=fuller --color=always {0}"

# Docker
[[cable_channel]]
name = "images"
source_command = "docker image list --format \"{{.ID}}\""
preview_command = "docker image inspect {0} | jq -C"

[[cable_channel]]
name = "containers"
source_command = "docker container list"
preview_command = "docker container inspect {0} | jq -C"

[[cable_channel]]
name = "networks"
source_command = "docker network list --format \"{{.Name}} - {{.Driver}}\""
preview_command = "docker network inspect {0} | jq -C"

[[cable_channel]]
name = "volumes"
source_command = "docker volume list --format \"{{.Name}} - {{.Driver}}\""
preview_command = "docker volume inspect {0} | jq -C"

# S3
[[cable_channel]]
name = "s3-buckets"
source_command = "aws s3 ls | cut -d \" \" -f 3"
preview_command = "aws s3 ls s3://{0}"

# Dotfiles
[[cable_channel]]
name = "my-dotfiles"
source_command = "fd -t f . $HOME/.config"
preview_command = ":files:"

# Shell history
[[cable_channel]]
name = "zsh-history"
source_command = "sed '1!G;h;$!d' $HOME/.zsh_history | cut -d\";\" -f 2-"

[[cable_channel]]
name = "bash-history"
source_command = "sed '1!G;h;$!d' $HOME/.bash_history"

[[cable_channel]]
name = "fish-history"
source_command = "fish -c 'history'"
